version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    restart: always
    ports:
      - '${DB_PORT}:5432' # host port:container port
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
